server:
  port: 8888

spring:
  config:
    import: optional:file:.env
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  prefix: api/v1
app:
  api-base-url: ${API_BASE_URL}
  client-base-url: ${CLIENT_BASE_URL}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}